apiVersion: v1
kind: Service
metadata:
  name: blur-service
spec:
  selector:
    app: blur
  ports:
    - port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blur
  template:
    metadata:
      labels:
        app: blur
    spec:
      containers:
      - name: blur
        image: blur-processor:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: REDIS_HOST
          value: "redis-service"