apiVersion: v1
kind: Service
metadata:
  name: web-api-service
spec:
  selector:
    app: web-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api
        image: web-api:v1
        imagePullPolicy: Never  # Important for local dev
        ports:
        - containerPort: 5000
        env:
        - name: BW_URL
          value: "http://bw-service:5001"
        - name: BLUR_URL
          value: "http://blur-service:5001"
        - name: REDIS_HOST
          value: "redis-service"